name: Manage EKS Cluster

on:
  workflow_dispatch:
    inputs:
      clusterName:
        description: 'Name of the EKS cluster'
        required: true
        default: 'my_eks_cluster'
      awsRegion:
        description: 'AWS Region for the cluster'
        required: true
        default: 'us-east-1'
      action:
        description: 'Action to perform (apply/destroy)'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  apply_cluster:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'apply' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform Init
      run: terraform init -upgrade
      working-directory: Terraform
    - name: Terraform Format
      run: terraform fmt
      working-directory: Terraform
    - name: Terraform Validate
      run: terraform validate
      working-directory: Terraform
    - name: Terraform Apply
      run: terraform apply -var="cluster_name=${{ github.event.inputs.clusterName }}" -var="region=${{ github.event.inputs.awsRegion }}" -auto-approve
      working-directory: Terraform

  destroy_cluster:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'destroy' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform Init
      run: terraform init -upgrade
      working-directory: Terraform
    - name: Terraform Format
      run: terraform fmt
      working-directory: Terraform
    - name: Terraform Validate
      run: terraform validate
      working-directory: Terraform
    - name: Terraform Destroy
      run: terraform destroy -var="cluster_name=${{ github.event.inputs.clusterName }}" -var="region=${{ github.event.inputs.awsRegion }}" -auto-approve
      working-directory: Terraform
