name: EKS Cluster and Node.js App Deployment

on:
  workflow_dispatch:
    inputs:
      clusterName:
        description: 'Name of the EKS cluster'
        required: true
        default: 'my_eks_cluster'
      awsRegion:
        description: 'AWS Region for the cluster'
        required: true
        default: 'us-east-1'
      action:
        description: 'Action to perform'
        required: true
        default: 'deploy_all'
        type: choice
        options:
          - deploy_all
          - deploy_app_only
          - destroy_all
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'kubernetes/**'
      - 'Dockerfile'
      - 'package.json'
      - '*.tf'

jobs:
  terraform:
    name: 'Terraform Cloud Infrastructure'
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'deploy_all' || github.event.inputs.action == 'destroy_all' || (github.event_name == 'push' && contains(join(github.event.commits.*.modified, ','), '.tf')) }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
    - name: Terraform Init
      id: init
      run: |
        terraform init

    - name: Terraform Validate
      id: validate
      run: |
        terraform validate

    - name: Update Terraform Variables
      run: |
        # Create a terraform.tfvars file with the input variables
        cat > terraform.tfvars << EOF
        region = "${{ github.event.inputs.awsRegion || 'us-east-1' }}"
        cluster_name = "${{ github.event.inputs.clusterName || 'my_eks_cluster' }}"
        EOF

    - name: Terraform Plan
      id: plan
      if: ${{ github.event.inputs.action != 'destroy_all' }}
      run: |
        terraform plan -var-file="terraform.tfvars" -input=false -out=tfplan
      continue-on-error: true

    - name: Terraform Apply
      id: apply
      if: ${{ github.event.inputs.action != 'destroy_all' }}
      run: |
        terraform apply -auto-approve tfplan
      
    - name: Terraform Destroy
      id: destroy
      if: ${{ github.event.inputs.action == 'destroy_all' }}
      run: |
        terraform destroy -var-file="terraform.tfvars" -auto-approve

    - name: Post-deployment configuration
      if: ${{ github.event.inputs.action != 'destroy_all' && steps.apply.outcome == 'success' }}
      run: |
        chmod +x ./post-deploy.sh
        ./post-deploy.sh
    
    - name: Output Cluster Info
      if: ${{ github.event.inputs.action != 'destroy_all' && steps.apply.outcome == 'success' }}
      run: |
        echo "Cluster Endpoint: $(terraform output -raw cluster_endpoint)"
        echo "Cluster Name: $(terraform output -raw cluster_name)"
        echo "::set-output name=cluster_name::$(terraform output -raw cluster_name)"
        echo "::set-output name=cluster_region::$(terraform output -raw region)"
        
  build_and_deploy:
    name: 'Build and Deploy App'
    runs-on: ubuntu-latest
    needs: [terraform]
    if: ${{ success() && (github.event.inputs.action == 'deploy_all' || github.event.inputs.action == 'deploy_app_only' || github.event_name == 'push') }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.awsRegion || 'us-east-1' }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Create ECR Repository if it doesn't exist
      run: |
        aws ecr describe-repositories --repository-names ${{ github.event.repository.name }} || \
        aws ecr create-repository --repository-name ${{ github.event.repository.name }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Generate image tag
      id: image-tag
      run: |
        TAG=$(echo $GITHUB_SHA | cut -c1-7)
        echo "tag=$TAG" >> $GITHUB_OUTPUT
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:${{ steps.image-tag.outputs.tag }}, ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:latest
    
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region ${{ github.event.inputs.awsRegion || 'us-east-1' }} --name ${{ github.event.inputs.clusterName || needs.terraform.outputs.cluster_name || 'my_eks_cluster' }}
    
    - name: Update Kubernetes manifests
      run: |
        # Replace placeholders in Kubernetes manifests
        ECR_REPOSITORY_URI="${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}"
        IMAGE_TAG="${{ steps.image-tag.outputs.tag }}"
        APP_NAME=$(basename ${{ github.repository }} | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9-]/-/g')
        
        # Process Kubernetes YAML files
        mkdir -p kubernetes/processed
        for file in kubernetes/*.yaml; do
          sed -e "s|\${ECR_REPOSITORY_URI}|$ECR_REPOSITORY_URI|g" \
              -e "s|latest|$IMAGE_TAG|g" \
              -e "s|nodejs-app|$APP_NAME|g" \
              "$file" > "kubernetes/processed/$(basename "$file")"
        done
    
    - name: Deploy to Kubernetes
      run: |
        APP_NAME=$(basename ${{ github.repository }} | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9-]/-/g')
        kubectl apply -f kubernetes/processed/
    
    - name: Verify deployment
      run: |
        APP_NAME=$(basename ${{ github.repository }} | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9-]/-/g')
        kubectl rollout status deployment/$APP_NAME
    
    - name: Get Service URL
      run: |
        APP_NAME=$(basename ${{ github.repository }} | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9-]/-/g')
        echo "Application deployed successfully!"
        echo "Service URL:"
        kubectl get service $APP_NAME-service -o jsonpath="{.status.loadBalancer.ingress[0].hostname}"
        echo ""
